CREATE OR REPLACE FORCE VIEW "CTAPO"."ERMS_CRC_VIEW" ("STUDYROLEID", "STUDYID", "CRC_NAME", "CRC_PHONE", "CRC_EMAIL", "TRANSFER_DATE") AS 
  (SELECT DISTINCT R.STUDYROLEID STUDYROLEID,
  S.STUDYID STUDYID,
  NVL( PRSN_N_FM_DTRY, PRSN_N_FRST ) || ' ' || DT.PRSN_N_LAST CRC_NAME,
  DT.PRAD_A_TLPH CRC_PHONE,
  DT.EMAD_N CRC_EMAIL,
  sysdate TRANSFER_DATE
FROM STUDY S
JOIN ERMSAPO.STUDYROLE R ON R.STUDYID = S.STUDYID
JOIN ERMSAPO.PERSON P ON P.PERSONID = R.PERSONID
JOIN ERMSAPO.DIRECTORY_TABLE DT ON P.DIRECTORYKEY = DT.PRSN_I_PBLC WHERE R.ROLETYPEID  = 1);