CREATE OR REPLACE FORCE VIEW "CTAPO"."ERMS_STUDY_REF_VIEW" ("STUDYID", "REFERENCE_NUMBER", "REFERENCE_DESC", "REFERENCE_TYPE_ID", "TRANSFER_DATE") AS 
  (SELECT S.STUDYID STUDYID, 
S.REFERENCENBR REFERENCE_NUMBER, 
R.REFERENCEDESC REFERENCE_DESC, 
R.REFERENCETYPEID REFERENCE_TYPE_ID, 
SYSDATE TRANSFER_DATE
FROM ERMSAPO.STUDYREFERENCE S
JOIN ERMSAPO.REFERENCETYPE R ON R.REFERENCETYPEID = S.REFERENCETYPEID
WHERE S.STUDYID IN (SELECT STUDYID FROM ERMS_STUDY_VIEW) AND R.REFERENCETYPEID IN (5,9));