  CREATE OR REPLACE FORCE VIEW "CTAPO"."ERMS_SUBSITE_VIEW" ("STUDYID", "LOCATION", "TRANSFER_DATE") AS 
  (SELECT S.STUDYID STUDYID,
SITE.LOCATION LOCATION,
SYSDATE TRANSFER_DATE
FROM STUDY S
JOIN STUDYSITE STUDYSITE ON STUDYSITE.STUDYID = S.STUDYID
JOIN ENROLLMENTLOCATION SITE ON SITE.ENROLLMENTLOCATIONID = STUDYSITE.ENROLLMENTLOCATIONID_SUBSITE);