CREATE OR REPLACE FORCE VIEW "CTAPO"."ERMS_STUDY_VIEW" ("STUDYID", "NCTID", "PI_NAME", "PI_PHONE", "PI_EMAIL", "DEPT", "DIV", "DEPT_DIV", "DEPT_DIV_SL_ID", "SPONSOR", "STUDY_PHASE", "STUDY_STATUS", "DISPLAY_IN_CLINICALTRIALS", "TITLE", "FULL_TITLE", "SYSDATE") AS 
  SELECT
  S.STUDYID AS STUDYID,
  SR.REFERENCENBR AS NCTID,
  NVL( PRSN_N_FM_DTRY, PRSN_N_FRST ) || ' ' || DT.PRSN_N_LAST AS PI_NAME,
  DT.PRAD_A_TLPH AS PI_PHONE,
  DT.EMAD_N AS PI_EMAIL,
  SLD.SECURITYDESC AS DEPT,
  SLV.SECURITYDESC AS DIV,
  NVL2( SLV.SECURITYDESC, SLV.SECURITYDESC, SLD.SECURITYDESC ) AS DEPT_DIV,
  NVL2( SLV.SECURITYLEVELID, SLV.SECURITYLEVELID, SLD.SECURITYLEVELID ) AS DEPT_DIV_SL_ID,
  SP.SPONSOR,
  SPH.PHASE AS STUDY_PHASE,
  SST.STUDYSTATUS AS STUDY_STATUS,
  SST.DISPLAY_IN_CLINICALTRIALS,
  S.BRIEFTITLE AS TITLE,
  S.TITLE AS FULL_TITLE,
  SYSDATE AS "SYSDATE"
FROM ERMSAPO.STUDY S
  INNER JOIN ERMSAPO.STUDYREFERENCE SR
    ON ( S.STUDYID = SR.STUDYID AND SR.REFERENCETYPEID = 6 AND SR.STATUS = 'A' )
  LEFT JOIN ERMSAPO.PERSON P
    ON ( S.PIID = P.PERSONID AND P.STATUS = 'A' )
  LEFT JOIN ERMSAPO.DIRECTORY_TABLE DT
    ON ( P.DIRECTORYKEY = DT.PRSN_I_PBLC )
  LEFT JOIN ERMSAPO.SECURITYLEVEL SLD
    ON S.DEPARTMENTID = SLD.SECURITYLEVELID
  LEFT JOIN ERMSAPO.SECURITYLEVEL SLV
    ON S.DIVISIONID = SLV.SECURITYLEVELID
  LEFT JOIN ERMSAPO.SPONSOR SP
    ON S.SPONSORID = SP.SPONSORID
  LEFT JOIN ERMSAPO.STUDYPHASE SPH
    ON S.PHASEID = SPH.STUDYPHASEID
  LEFT JOIN ERMSAPO.STUDYSTATUS SST
    ON S.STUDYSTATUSID = SST.STUDYSTATUSID
    WHERE SR.REFERENCENBR like 'NCT%' AND SLD.SECURITYLEVELID != 'D22' AND SST.STUDYSTATUSID IN (1,4,8,12,13);